---
title: "Powerplant Power Regression
author: "Daniel Lundstrom"
output:
  word_document: default
  html_document: default
  pdf_document: default
---

```{r fitting_dcp}

# fit power and 

RSS.lm1 = NULL;
RSS.lm2 = NULL;
TSS = NULL;
r2.lm1 = NULL;
r2.lm2 = NULL
coeff.lm = NULL;

for (i in 1:22){
  plot(p1nz$IRRADIATION,p1nz[,i+5]);
  
  lm.fit=lm(p1nz[,i+5]~IRRADIATION+AMBIENT_TEMPERATURE,data=p1nz);
  RSS.lm1[i] = mean((p1nz[,i+5]-predict(lm.fit,p1nz))^2);
  points(p1nz$IRRADIATION,predict(lm.fit,p1nz),col="red")
  
  lm.fit=lm(p1nz[,i+5]~poly(IRRADIATION,2)+AMBIENT_TEMPERATURE,data=p1nz);
  RSS.lm2[i] = mean((p1nz[,i+5]-predict(lm.fit,p1nz))^2);
  points(p1nz$IRRADIATION,predict(lm.fit,p1nz),col="blue")
  
  TSS[i] = mean((p1nz[,i+5]-mean(p1nz[,i+5]))^2);
  r2.lm1[i] = 1-RSS.lm1[i]/TSS[i];
  r2.lm2[i] = 1-RSS.lm2[i]/TSS[i];
}

r2.lm2-r2.lm1

for (i in 1:22){
  plot(p1nz$IRRADIATION,p1nz[,i+5]);
  
  lm.fit=lm(p1nz[,i+5]~IRRADIATION+AMBIENT_TEMPERATURE,data=p1nz);
  RSS.lm1[i] = mean((p1nz[,i+5]-predict(lm.fit,p1nz))^2);
  points(p1nz$IRRADIATION,predict(lm.fit,p1nz),col="red")
  
  lm.fit=lm(as.formula(paste(colnames(p1nz)[i+5],"~.")),data=p1nz);
  RSS.lm2[i] = mean((p1nz[,i+5]-predict(lm.fit,p1nz))^2);
  points(p1nz$IRRADIATION,predict(lm.fit,p1nz),col="blue")
  
  TSS[i] = mean((p1nz[,i+5]-mean(p1nz[,i+5]))^2);
  r2.lm1[i] = 1-RSS.lm1[i]/TSS[i];
  r2.lm2[i] = 1-RSS.lm2[i]/TSS[i];
}

r2.lm2-r2.lm1






# illustrates that different sources have different curves.

plot(p1nz$IRRADIATION, p1nz$Edcp, col="orange")
points(p1nz$IRRADIATION, p1nz$Fdcp, col="black")


```

```{r test1}
#find potential failures

bad.points = NULL;
sd.error = 4;
history.memory = 8;


for (i in 1:1){
  
  mod=lm(p1nz[,i+5]~poly(IRRADIATION,2),data=p1nz);
  variance = var(p1nz[,i+5]-predict(mod,p1nz));
  sd = sqrt(variance);
  
  for (j in 1:length(p1$DAY)){
    
    if (p1[j,i+5]<predict(mod,p1[j,])-sd.error*sd){
      bad.points[j]=TRUE;
    } else {
      bad.points[j] = FALSE;
    }
  }
  

  bad.point.history = matrix(0,history.memory+1,length(p1$DAY[bad.points]));
  bad.point.count=0
  
  for (j in 1:length(bad.points)){
    if (bad.points[j]){
      bad.point.count = bad.point.count + 1;
      bad.point.history[,bad.point.count] = (j-history.memory):j;
      
    }
      
  }
  
  
  plot(p1$IRRADIATION,predict(mod,p1),main = paste("Predicting Faileurs of",colnames(p1)[i+5]), xlab = "Irradiation", 
       ylab = "Direct Current Power",pch=20);
  points(p1$IRRADIATION[bad.point.history[,2]],p1[bad.point.history[,2],i+5],col="blue",pch=20)
  
  
    plot(p1$IRRADIATION,predict(mod,p1),main = paste("Predicting Faileurs of",colnames(p1)[i+5]), xlab = "Irradiation", 
         ylab = "Direct Current Power",pch=20);
  points(p1$IRRADIATION[!bad.points],p1[!bad.points,i+5],col="blue",pch=20)
  points(p1$IRRADIATION[bad.points],p1[bad.points,i+5],col="red",pch=20)
  
}




```


```{r test2}
#find potential failures

for (j in 1:bad.point.count){
  
  plot(p1$IRRADIATION,predict(mod,p1),main = paste("Predicting Faileurs of",colnames(p1)[i+5]), xlab = "Irradiation", 
       ylab = "Direct Current Power",pch=20);
  points(p1$IRRADIATION[bad.point.history[,j]],p1[bad.point.history[,j],i+5],col="blue",pch=20)

}




```


```{r find faileurs}

bad.points = NULL;
sd.error = 4;


for (i in 9:13){
  
  mod=lm(p1nz[,i+5]~poly(IRRADIATION,2),data=p1nz);
  variance = var(p1nz[,i+5]-predict(mod,p1nz));
  sd = sqrt(variance);
  
  for (j in 1:length(p1$DAY)){
    
    if (p1[j,i+5]<predict(mod,p1[j,])-sd.error*sd){
      bad.points[j]=TRUE;
    } else {
      bad.points[j] = FALSE;
    }
    
    
  }
  
}


```

```{r spline}
library(splines);
RSS.mod1 = NULL;
RSS.mod2 = NULL;
RSS.mod3 = NULL;
TSS = NULL;
r2.spline1 = NULL;
r2.spline2 = NULL;
r2.spline3 = NULL;


num.plots = 1;

IRRlims = range(p1nz$IRRADIATION);
IRR.grid = seq(from=IRRlims[1],to=IRRlims[2]);


for (i in 1:1){

  mod.fit1=lm(as.formula(paste(colnames(p1nz)[i+5],"~bs(IRRADIATION,knots=c(0.4,0.8))")),data=p1nz);
  list(IRRADIATION = IRR.grid)
  pred1 = predict(mod.fit1,newdata=list(IRRADIATION=p1nz$IRRADIATION),se=T);
  RSS.mod1[i] = mean((p1nz[,i+5]-pred1$fit)^2);
  
  mod.fit2=lm(as.formula(paste(colnames(p1nz)[i+5],"~bs(IRRADIATION,knots=c(0.4,0.6,0.8))")),data=p1nz);
  list(IRRADIATION = IRR.grid)
  pred2 = predict(mod.fit2,newdata=list(IRRADIATION=p1nz$IRRADIATION),se=T);
  RSS.mod2[i] = mean((p1nz[,i+5]-pred2$fit)^2);
  
  mod.fit3=lm(as.formula(paste(colnames(p1nz)[i+5],"~bs(IRRADIATION,knots=c(0.4,0.6,0.8,1))")),data=p1nz);
  list(IRRADIATION = IRR.grid)
  pred3 = predict(mod.fit3,newdata=list(IRRADIATION=p1nz$IRRADIATION),se=T);
  RSS.mod3[i] = mean((p1nz[,i+5]-pred3$fit)^2);

  TSS[i] = mean((p1nz[,i+5]-mean(p1nz[,i+5]))^2);
  r2.spline1[i] = 1-RSS.mod1[i]/TSS[i];
  r2.spline2[i] = 1-RSS.mod2[i]/TSS[i];
  r2.spline3[i] = 1-RSS.mod3[i]/TSS[i];
  
  if (i <= num.plots){
    plot(p1nz$IRRADIATION,p1nz[,i+5],main = paste("Ridge Regression Fits of",colnames(p1nz)[i+5], "with polynomial Irradiation"),     xlab = "Irradiation", ylab = "Direct Current Power");
    points(p1nz$IRRADIATION,pred1$fit,col="red",pch=20)
    points(p1nz$IRRADIATION,pred2$fit,col="blue",pch=20)
    points(p1nz$IRRADIATION,pred3$fit,col="green",pch=20)
    
  }
}

mean(r2.spline1);
mean(r2.spline2);
mean(r2.spline3);

var(r2.spline3)
```



```{r lasso}
library(glmnet);
RSS.mod1 = NULL;
RSS.mod2 = NULL;
RSS.mod3 = NULL;
TSS = NULL;
r2.lasso1 = NULL;
r2.lasso2 = NULL;
r2.lasso3 = NULL;

coeff.lm = NULL;
num.plots =2;

for (i in 1:22){
  
  #plot(p1nz$IRRADIATION,p1nz[,i+5],main = paste("Ridge Regression Fits of",colnames(p1nz)[i+5], "with polynomial Irradiation"),     xlab = "Irradiation", ylab = "Direct Current Power");
  
  x1 = model.matrix(as.formula(paste(colnames(p1nz)[i+5],"~poly(IRRADIATION,1)+AMBIENT_TEMPERATURE")),p1nz)[,-1];
  y1 = p1nz[,i+5];
  mod.fit1=cv.glmnet(x1,y1,type.measure = "mse",alpha=1);
  RSS.mod1[i] = mean((p1nz[,i+5]-predict(mod.fit1,s=mod.fit1$lambda.min,newx=x1))^2);
  #points(p1nz$IRRADIATION,predict(mod.fit1,s=mod.fit1$lambda.min,newx=x1),col="red",pch=20)
  
  x2 = model.matrix(as.formula(paste(colnames(p1nz)[i+5],"~poly(IRRADIATION,2)+AMBIENT_TEMPERATURE")),p1nz)[,-1];
  y2 = p1nz[,i+5];
  mod.fit2=cv.glmnet(x2,y2,type.measure = "mse",alpha=1);
  RSS.mod2[i] = mean((p1nz[,i+5]-predict(mod.fit2,s=mod.fit2$lambda.min,newx=x2))^2);
  #points(p1nz$IRRADIATION,predict(mod.fit2,s=mod.fit2$lambda.min,newx=x2),col="blue",pch=20)
  
  x3 = model.matrix(as.formula(paste(colnames(p1nz)[i+5],"~poly(IRRADIATION,3)+AMBIENT_TEMPERATURE")),p1nz)[,-1];
  y3 = p1nz[,i+5];
  mod.fit3=cv.glmnet(x3,y3,type.measure = "mse",alpha=1);
  RSS.mod3[i] = mean((p1nz[,i+5]-predict(mod.fit3,s=mod.fit3$lambda.min,newx=x3))^2);
  #points(p1nz$IRRADIATION,predict(mod.fit3,s=mod.fit3$lambda.min,newx=x3),col="green",pch=20)
  
  
  TSS[i] = mean((p1nz[,i+5]-mean(p1nz[,i+5]))^2);
  r2.lasso1[i] = 1-RSS.mod1[i]/TSS[i];
  r2.lasso2[i] = 1-RSS.mod2[i]/TSS[i];
  r2.lasso3[i] = 1-RSS.mod3[i]/TSS[i];
  
  if (i <= num.plots){
    plot(p1nz$IRRADIATION,p1nz[,i+5],main = paste("Lasso Regression Fits of",colnames(p1nz)[i+5], "with polynomial Irradiation"),     xlab = "Irradiation", ylab = "Direct Current Power");
  points(p1nz$IRRADIATION,predict(mod.fit1,s=mod.fit1$lambda.min,newx=x1),col="red",pch=20)
  points(p1nz$IRRADIATION,predict(mod.fit2,s=mod.fit2$lambda.min,newx=x2),col="blue",pch=20)
  #points(p1nz$IRRADIATION,predict(mod.fit3,s=mod.fit3$lambda.min,newx=x3),col="green",pch=20)
  }
  
}
  #third degree hugs pretty well
  plot(p1nz$IRRADIATION,p1nz[,i+5],main = paste("Lasso Regression Fits of",colnames(p1nz)[i+5], "with polynomial Irradiation"),     xlab = "Irradiation", ylab = "Direct Current Power");
  points(p1nz$IRRADIATION,predict(mod.fit3,s=mod.fit3$lambda.min,newx=x3),col="green",pch=20)

mean(r2.lasso1)
mean(r2.lasso2)
mean(r2.lasso3)

var(r2.lasso3)


```

```{r ridge}
library(glmnet);
RSS.mod1 = NULL;
RSS.mod2 = NULL;
RSS.mod3 = NULL;
TSS = NULL;
r2.ridge1 = NULL;
r2.ridge2 = NULL;
r2.ridge3 = NULL;

coeff.lm = NULL;

num.plots = 2;

for (i in 1:22){
  
  #plot(p1nz$IRRADIATION,p1nz[,i+5],main = paste("Ridge Regression Fits of",colnames(p1nz)[i+5], "with polynomial Irradiation"),     xlab = "Irradiation", ylab = "Direct Current Power");
  
  x1 = model.matrix(as.formula(paste(colnames(p1nz)[i+5],"~poly(IRRADIATION,1)+AMBIENT_TEMPERATURE")),p1nz)[,-1];
  y1 = p1nz[,i+5];
  mod.fit1=cv.glmnet(x1,y1,type.measure = "mse",alpha=0);
  RSS.mod1[i] = mean((p1nz[,i+5]-predict(mod.fit1,s=mod.fit1$lambda.min,newx=x1))^2);
  #points(p1nz$IRRADIATION,predict(mod.fit1,s=mod.fit1$lambda.min,newx=x1),col="red",pch=20)
  
  x2 = model.matrix(as.formula(paste(colnames(p1nz)[i+5],"~poly(IRRADIATION,2)+AMBIENT_TEMPERATURE")),p1nz)[,-1];
  y2 = p1nz[,i+5];
  mod.fit2=cv.glmnet(x2,y2,type.measure = "mse",alpha=0);
  RSS.mod2[i] = mean((p1nz[,i+5]-predict(mod.fit2,s=mod.fit2$lambda.min,newx=x2))^2);
  #points(p1nz$IRRADIATION,predict(mod.fit2,s=mod.fit2$lambda.min,newx=x2),col="blue",pch=20)
  
  x3 = model.matrix(as.formula(paste(colnames(p1nz)[i+5],"~poly(IRRADIATION,3)+AMBIENT_TEMPERATURE")),p1nz)[,-1];
  y3 = p1nz[,i+5];
  mod.fit3=cv.glmnet(x3,y3,type.measure = "mse",alpha=0);
  RSS.mod3[i] = mean((p1nz[,i+5]-predict(mod.fit3,s=mod.fit3$lambda.min,newx=x3))^2);
  #points(p1nz$IRRADIATION,predict(mod.fit3,s=mod.fit3$lambda.min,newx=x3),col="green",pch=20)
  
  
  TSS[i] = mean((p1nz[,i+5]-mean(p1nz[,i+5]))^2);
  r2.ridge1[i] = 1-RSS.mod1[i]/TSS[i];
  r2.ridge2[i] = 1-RSS.mod2[i]/TSS[i];
  r2.ridge3[i] = 1-RSS.mod3[i]/TSS[i];
  
  if (i<= num.plots){
    plot(p1nz$IRRADIATION,p1nz[,i+5],main = paste("Ridge Regression Fits of",colnames(p1nz)[i+5], "with polynomial    
        Irradiation"),     xlab = "Irradiation", ylab = "Direct Current Power");
    points(p1nz$IRRADIATION,predict(mod.fit1,s=mod.fit1$lambda.min,newx=x1),col="red",pch=20)
    points(p1nz$IRRADIATION,predict(mod.fit2,s=mod.fit2$lambda.min,newx=x2),col="blue",pch=20)
    points(p1nz$IRRADIATION,predict(mod.fit3,s=mod.fit3$lambda.min,newx=x3),col="green",pch=20)
  }
  
}

mean(r2.ridge1)
mean(r2.ridge2)
mean(r2.ridge3)

var(r2.ridge3)


```


```{r basic polynomial fits}
# linear and 2nd-4th degree polynomials

RSS.mod1 = NULL;
RSS.mod2 = NULL;
RSS.mod3 = NULL;
TSS = NULL;
r2.lm1 = NULL;
r2.lm2 = NULL;
r2.lm3 = NULL;

coeff.lm = NULL;
num.plots = 2;

for (i in 1:22){
  #plot(p1nz$IRRADIATION,p1nz[,i+5],main = paste("Linear Regression Fits of",colnames(p1nz)[i+5], "with polynomial Irradiation"),     xlab = "Irradiation", ylab = "Direct Current Power");
  
  mod.fit1=lm(p1nz[,i+5]~IRRADIATION+AMBIENT_TEMPERATURE,data=p1nz);
  RSS.mod1[i] = mean((p1nz[,i+5]-predict(mod.fit1,p1nz))^2);
  
  mod.fit2=lm(p1nz[,i+5]~poly(IRRADIATION,2)+AMBIENT_TEMPERATURE,data=p1nz);
  RSS.mod2[i] = mean((p1nz[,i+5]-predict(mod.fit2,p1nz))^2);
  
  mod.fit3=lm(p1nz[,i+5]~poly(IRRADIATION,3)+AMBIENT_TEMPERATURE,data=p1nz);
  RSS.mod3[i] = mean((p1nz[,i+5]-predict(mod.fit3,p1nz))^2);
  
  
  TSS[i] = mean((p1nz[,i+5]-mean(p1nz[,i+5]))^2);
  r2.lm1[i] = 1-RSS.mod1[i]/TSS[i];
  r2.lm2[i] = 1-RSS.mod2[i]/TSS[i];
  r2.lm3[i] = 1-RSS.mod3[i]/TSS[i];
  
  if (i<=num.plots){
  plot(p1nz$IRRADIATION,p1nz[,i+5],main = paste("Linear Regression Fits of",colnames(p1nz)[i+5], "with polynomial 
      Irradiation"), xlab = "Irradiation", ylab = "Direct Current Power");
  points(p1nz$IRRADIATION,predict(mod.fit1,p1nz),col="red",pch=20)
  points(p1nz$IRRADIATION,predict(mod.fit2,p1nz),col="blue",pch=20)
  #points(p1nz$IRRADIATION,predict(mod.fit3,p1nz),col="green",pch=20)
  }
}

mean(r2.lm1)
mean(r2.lm2)
mean(r2.lm3)


var(r2.lm3)

```

```{r 2nd degree fits with different predictors}
# linear and 2nd-4th degree polynomials

RSS.mod1 = NULL;
RSS.mod2 = NULL;
RSS.mod3 = NULL;
RSS.mod4 = NULL;
RSS.lmod1 = NULL;
RSS.lmod2 = NULL;
RSS.lmod3 = NULL;
RSS.lmod4 = NULL;
TSS = NULL;
r2.lm1 = NULL;
r2.lm2 = NULL;
r2.lm3 = NULL;
r2.lm4 = NULL;
r2.llm1 = NULL;
r2.llm2 = NULL;
r2.llm3 = NULL;
r2.llm4 = NULL;

coeff.lm = NULL;

for (i in 1:22){
  
  x1 = model.matrix(as.formula(paste(colnames(p1nz)[i+5],"~poly(IRRADIATION,2)")),p1nz)[,-1];
  y1 = p1nz[,i+5];
  mod.fit1=cv.glmnet(x1,y1,type.measure = "mse",alpha=1);
  RSS.lmod1[i] = mean((p1nz[,i+5]-predict(mod.fit1,s=mod.fit1$lambda.min,newx=x1))^2);
  
  x1 = model.matrix(as.formula(paste(colnames(p1nz)[i+5],"~poly(IRRADIATION,2)+AMBIENT_TEMPERATURE")),p1nz)[,-1];
  y1 = p1nz[,i+5];
  mod.fit1=cv.glmnet(x1,y1,type.measure = "mse",alpha=1);
  RSS.lmod2[i] = mean((p1nz[,i+5]-predict(mod.fit1,s=mod.fit1$lambda.min,newx=x1))^2);
  
  x1 = model.matrix(as.formula(paste(colnames(p1nz)[i+5],"~poly(IRRADIATION,2)+MODULE_TEMPERATURE")),p1nz)[,-1];
  y1 = p1nz[,i+5];
  mod.fit1=cv.glmnet(x1,y1,type.measure = "mse",alpha=1);
  RSS.lmod3[i] = mean((p1nz[,i+5]-predict(mod.fit1,s=mod.fit1$lambda.min,newx=x1))^2);
  
  x1 = model.matrix(as.formula(paste(colnames(p1nz)[i+5],"~poly(IRRADIATION,2)+AMBIENT_TEMPERATURE+MODULE_TEMPERATURE")),p1nz)[,-1];
  y1 = p1nz[,i+5];
  mod.fit1=cv.glmnet(x1,y1,type.measure = "mse",alpha=1);
  RSS.lmod4[i] = mean((p1nz[,i+5]-predict(mod.fit1,s=mod.fit1$lambda.min,newx=x1))^2);
  
  
  mod.fit1=lm(p1nz[,i+5]~poly(IRRADIATION,2),data=p1nz);
  RSS.mod1[i] = mean((p1nz[,i+5]-predict(mod.fit1,p1nz))^2);
  
  mod.fit2=lm(p1nz[,i+5]~poly(IRRADIATION,2)+AMBIENT_TEMPERATURE,data=p1nz);
  RSS.mod2[i] = mean((p1nz[,i+5]-predict(mod.fit2,p1nz))^2);
  
  mod.fit3=lm(p1nz[,i+5]~poly(IRRADIATION,2)+MODULE_TEMPERATURE,data=p1nz);
  RSS.mod3[i] = mean((p1nz[,i+5]-predict(mod.fit3,p1nz))^2);
  
  mod.fit4=lm(p1nz[,i+5]~poly(IRRADIATION,2)+MODULE_TEMPERATURE+AMBIENT_TEMPERATURE,data=p1nz);
  RSS.mod4[i] = mean((p1nz[,i+5]-predict(mod.fit4,p1nz))^2);
  
  
  TSS[i] = mean((p1nz[,i+5]-mean(p1nz[,i+5]))^2);
  r2.lm1[i] = 1-RSS.mod1[i]/TSS[i];
  r2.lm2[i] = 1-RSS.mod2[i]/TSS[i];
  r2.lm3[i] = 1-RSS.mod3[i]/TSS[i];
  r2.lm4[i] = 1-RSS.mod4[i]/TSS[i];
  r2.llm1[i] = 1-RSS.lmod1[i]/TSS[i];
  r2.llm2[i] = 1-RSS.lmod2[i]/TSS[i];
  r2.llm3[i] = 1-RSS.lmod3[i]/TSS[i];
  r2.llm4[i] = 1-RSS.lmod4[i]/TSS[i];
  

}

mean(r2.lm1)
mean(r2.lm2)
mean(r2.lm3)
mean(r2.lm4)
mean(r2.llm1)
mean(r2.llm2)
mean(r2.llm3)
mean(r2.llm4)




```

```{r illustrations}

#illustrates that higher temperatures cause an increase in variance.

plot(p1nz$IRRADIATION[p1nz$AMBIENT_TEMPERATURE>28], p1nz$Adcp[p1nz$AMBIENT_TEMPERATURE>28],col="red")
points(p1nz$IRRADIATION[p1nz$AMBIENT_TEMPERATURE<28], p1nz$Adcp[p1nz$AMBIENT_TEMPERATURE<28],col="blue")

plot(p1nz$IRRADIATION[p1nz$AMBIENT_TEMPERATURE>29], p1nz$Adcp[p1nz$AMBIENT_TEMPERATURE>29],col="red")
points(p1nz$IRRADIATION[p1nz$AMBIENT_TEMPERATURE<29], p1nz$Adcp[p1nz$AMBIENT_TEMPERATURE<29],col="blue")


```



```{r test}
  summary(mod.fit1)

```



```{r bag_of_holding}
#plot(p1nzgen$IRRADIATION[p1nzgen$SOURCE == "A"], p1nzgen$DC_POWER[p1nzgen$SOURCE == "A"],col="blue")

#points(p1nzgen$IRRADIATION[p1nzgen$SOURCE == "B"], p1nzgen$DC_POWER[p1nzgen$SOURCE == "B"],col="red")

#points(p1nzgen$IRRADIATION[p1nzgen$SOURCE == "C"], p1nzgen$DC_POWER[p1nzgen$SOURCE == "C"], col="green")
#points(p1nzgen$IRRADIATION[p1nzgen$SOURCE == "D"], p1nzgen$DC_POWER[p1nzgen$SOURCE == "D"], col="purple")

#points(p1nzgen$IRRADIATION[p1nzgen$SOURCE == "E"], p1nzgen$DC_POWER[p1nzgen$SOURCE == "E"], col="black")

#points(p1nzgen$IRRADIATION[p1nzgen$SOURCE == "F"], p1nzgen$DC_POWER[p1nzgen$SOURCE == "F"], col="orange")

#plot(p1nzsen$TIME[p1nzsen$DAY == 1], p1nzsen$IRRADIATION[p1nzsen$DAY == 1],col="red")
#plot(p1nzsen$TIME[p1nzsen$DAY == 2], p1nzsen$IRRADIATION[p1nzsen$DAY == 2],col="red")
#plot(p1nzsen$TIME[p1nzsen$DAY == 3], p1nzsen$IRRADIATION[p1nzsen$DAY == 3],col="red")
#plot(p1nzsen$TIME[p1nzsen$DAY == 4], p1nzsen$IRRADIATION[p1nzsen$DAY == 4],col="red")




#plot(p1nzgen$IRRADIATION, p1nzgen$DC_POWER)
#n=28
#plot(p1nzgen$IRRADIATION[p1nzgen$AMBIENT_TEMPERATURE>n], p1nzgen$DC_POWER[p1nzgen$AMBIENT_TEMPERATURE>n],col="red")
#length(p1nzgen$IRRADIATION[p1nzgen$AMBIENT_TEMPERATURE>n])
#points(p1nzgen$IRRADIATION[p1nzgen$AMBIENT_TEMPERATURE<n], p1nzgen$DC_POWER[p1nzgen$AMBIENT_TEMPERATURE<n],col="blue")
#length(p1nzgen$IRRADIATION[p1nzgen$AMBIENT_TEMPERATURE<n])

```
